#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UDQL")]
	public partial class UDQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBenh(Benh instance);
    partial void UpdateBenh(Benh instance);
    partial void DeleteBenh(Benh instance);
    partial void InsertThuoc(Thuoc instance);
    partial void UpdateThuoc(Thuoc instance);
    partial void DeleteThuoc(Thuoc instance);
    partial void InsertBenhNhan(BenhNhan instance);
    partial void UpdateBenhNhan(BenhNhan instance);
    partial void DeleteBenhNhan(BenhNhan instance);
    partial void InsertCachDung(CachDung instance);
    partial void UpdateCachDung(CachDung instance);
    partial void DeleteCachDung(CachDung instance);
    partial void InsertDonVi(DonVi instance);
    partial void UpdateDonVi(DonVi instance);
    partial void DeleteDonVi(DonVi instance);
    partial void InsertDSKhamBenh(DSKhamBenh instance);
    partial void UpdateDSKhamBenh(DSKhamBenh instance);
    partial void DeleteDSKhamBenh(DSKhamBenh instance);
    partial void InsertTaiKhoan(TaiKhoan instance);
    partial void UpdateTaiKhoan(TaiKhoan instance);
    partial void DeleteTaiKhoan(TaiKhoan instance);
    partial void InsertThamSo(ThamSo instance);
    partial void UpdateThamSo(ThamSo instance);
    partial void DeleteThamSo(ThamSo instance);
    #endregion
		
		public UDQLDataContext() : 
				base(global::doan.Properties.Settings.Default.UDQLConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public UDQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UDQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UDQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public UDQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Benh> Benhs
		{
			get
			{
				return this.GetTable<Benh>();
			}
		}
		
		public System.Data.Linq.Table<Thuoc> Thuocs
		{
			get
			{
				return this.GetTable<Thuoc>();
			}
		}
		
		public System.Data.Linq.Table<BenhNhan> BenhNhans
		{
			get
			{
				return this.GetTable<BenhNhan>();
			}
		}
		
		public System.Data.Linq.Table<CachDung> CachDungs
		{
			get
			{
				return this.GetTable<CachDung>();
			}
		}
		
		public System.Data.Linq.Table<DonVi> DonVis
		{
			get
			{
				return this.GetTable<DonVi>();
			}
		}
		
		public System.Data.Linq.Table<DSKhamBenh> DSKhamBenhs
		{
			get
			{
				return this.GetTable<DSKhamBenh>();
			}
		}
		
		public System.Data.Linq.Table<TaiKhoan> TaiKhoans
		{
			get
			{
				return this.GetTable<TaiKhoan>();
			}
		}
		
		public System.Data.Linq.Table<ThamSo> ThamSos
		{
			get
			{
				return this.GetTable<ThamSo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau1")]
		public int cau1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau9")]
		public int cau9([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau10")]
		public int cau10([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau11")]
		public int cau11([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mathuoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mathuoc, soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau12")]
		public int cau12([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mabn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hoten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> namsinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(5)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string chieutrung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabn, hoten, gioitinh, namsinh, diachi, chieutrung);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau13")]
		public ISingleResult<cau13Result> cau13([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngay);
			return ((ISingleResult<cau13Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau14")]
		public int cau14([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string makb, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string mabn, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mabenh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mathuoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sl, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string macd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makb, mabn, mabenh, mathuoc, sl, macd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau15")]
		public ISingleResult<cau15Result> cau15()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cau15Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau16")]
		public ISingleResult<cau16Result> cau16()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<cau16Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau17")]
		public ISingleResult<cau17Result> cau17([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mabn)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabn);
			return ((ISingleResult<cau17Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau18")]
		public ISingleResult<cau18Result> cau18([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<cau18Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau19")]
		public ISingleResult<cau19Result> cau19([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
			return ((ISingleResult<cau19Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau20")]
		public void cau20()
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau21")]
		public void cau21()
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau22")]
		public void cau22([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string makb)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makb);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau23")]
		public void cau23([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau24")]
		public void cau24([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> thang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> nam)
		{
			this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), thang, nam);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau25")]
		public int cau25([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mathuoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string donvi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> gia, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sl)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mathuoc, ten, donvi, gia, sl);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau26")]
		public int cau26([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mathuoc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mathuoc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau27")]
		public int cau27([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mabenh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tenbenh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabenh, tenbenh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau28")]
		public int cau28([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mabenh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mabenh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau29")]
		public int cau29([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string macd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tencd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), macd, tencd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau3")]
		public int cau3([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau30")]
		public int cau30([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string macd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), macd);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau31")]
		public int cau31([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string madv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string tendv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), madv, tendv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau32")]
		public int cau32([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string madv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), madv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau4")]
		public int cau4([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), password, username);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau5")]
		public int cau5([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau6")]
		public int cau6([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau7")]
		public int cau7([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.cau8")]
		public int cau8([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), soluong);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Benh")]
	public partial class Benh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBenh;
		
		private string _TenBenh;
		
		private EntitySet<DSKhamBenh> _DSKhamBenhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBenhChanging(string value);
    partial void OnMaBenhChanged();
    partial void OnTenBenhChanging(string value);
    partial void OnTenBenhChanged();
    #endregion
		
		public Benh()
		{
			this._DSKhamBenhs = new EntitySet<DSKhamBenh>(new Action<DSKhamBenh>(this.attach_DSKhamBenhs), new Action<DSKhamBenh>(this.detach_DSKhamBenhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenh", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBenh
		{
			get
			{
				return this._MaBenh;
			}
			set
			{
				if ((this._MaBenh != value))
				{
					this.OnMaBenhChanging(value);
					this.SendPropertyChanging();
					this._MaBenh = value;
					this.SendPropertyChanged("MaBenh");
					this.OnMaBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenh", DbType="NVarChar(50)")]
		public string TenBenh
		{
			get
			{
				return this._TenBenh;
			}
			set
			{
				if ((this._TenBenh != value))
				{
					this.OnTenBenhChanging(value);
					this.SendPropertyChanging();
					this._TenBenh = value;
					this.SendPropertyChanged("TenBenh");
					this.OnTenBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Benh_DSKhamBenh", Storage="_DSKhamBenhs", ThisKey="MaBenh", OtherKey="MaBenh")]
		public EntitySet<DSKhamBenh> DSKhamBenhs
		{
			get
			{
				return this._DSKhamBenhs;
			}
			set
			{
				this._DSKhamBenhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.Benh = this;
		}
		
		private void detach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.Benh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Thuoc")]
	public partial class Thuoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaThuoc;
		
		private string _TenThuoc;
		
		private string _MaDonVi;
		
		private System.Nullable<int> _Gia;
		
		private System.Nullable<int> _SlTon;
		
		private EntitySet<DSKhamBenh> _DSKhamBenhs;
		
		private EntityRef<DonVi> _DonVi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnTenThuocChanging(string value);
    partial void OnTenThuocChanged();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnSlTonChanging(System.Nullable<int> value);
    partial void OnSlTonChanged();
    #endregion
		
		public Thuoc()
		{
			this._DSKhamBenhs = new EntitySet<DSKhamBenh>(new Action<DSKhamBenh>(this.attach_DSKhamBenhs), new Action<DSKhamBenh>(this.detach_DSKhamBenhs));
			this._DonVi = default(EntityRef<DonVi>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this.OnTenThuocChanging(value);
					this.SendPropertyChanging();
					this._TenThuoc = value;
					this.SendPropertyChanged("TenThuoc");
					this.OnTenThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="VarChar(10)")]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					if (this._DonVi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
		public System.Nullable<int> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SlTon", DbType="Int")]
		public System.Nullable<int> SlTon
		{
			get
			{
				return this._SlTon;
			}
			set
			{
				if ((this._SlTon != value))
				{
					this.OnSlTonChanging(value);
					this.SendPropertyChanging();
					this._SlTon = value;
					this.SendPropertyChanged("SlTon");
					this.OnSlTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_DSKhamBenh", Storage="_DSKhamBenhs", ThisKey="MaThuoc", OtherKey="MaThuoc")]
		public EntitySet<DSKhamBenh> DSKhamBenhs
		{
			get
			{
				return this._DSKhamBenhs;
			}
			set
			{
				this._DSKhamBenhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonVi_Thuoc", Storage="_DonVi", ThisKey="MaDonVi", OtherKey="MaDonVi", IsForeignKey=true)]
		public DonVi DonVi
		{
			get
			{
				return this._DonVi.Entity;
			}
			set
			{
				DonVi previousValue = this._DonVi.Entity;
				if (((previousValue != value) 
							|| (this._DonVi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DonVi.Entity = null;
						previousValue.Thuocs.Remove(this);
					}
					this._DonVi.Entity = value;
					if ((value != null))
					{
						value.Thuocs.Add(this);
						this._MaDonVi = value.MaDonVi;
					}
					else
					{
						this._MaDonVi = default(string);
					}
					this.SendPropertyChanged("DonVi");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = this;
		}
		
		private void detach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.Thuoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BenhNhan")]
	public partial class BenhNhan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBN;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NamSinh;
		
		private string _DiaChi;
		
		private string _TrieuChung;
		
		private EntitySet<DSKhamBenh> _DSKhamBenhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBNChanging(string value);
    partial void OnMaBNChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNamSinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNamSinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTrieuChungChanging(string value);
    partial void OnTrieuChungChanged();
    #endregion
		
		public BenhNhan()
		{
			this._DSKhamBenhs = new EntitySet<DSKhamBenh>(new Action<DSKhamBenh>(this.attach_DSKhamBenhs), new Action<DSKhamBenh>(this.detach_DSKhamBenhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this.OnMaBNChanging(value);
					this.SendPropertyChanging();
					this._MaBN = value;
					this.SendPropertyChanged("MaBN");
					this.OnMaBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this.OnNamSinhChanging(value);
					this.SendPropertyChanging();
					this._NamSinh = value;
					this.SendPropertyChanged("NamSinh");
					this.OnNamSinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChung", DbType="NVarChar(50)")]
		public string TrieuChung
		{
			get
			{
				return this._TrieuChung;
			}
			set
			{
				if ((this._TrieuChung != value))
				{
					this.OnTrieuChungChanging(value);
					this.SendPropertyChanging();
					this._TrieuChung = value;
					this.SendPropertyChanged("TrieuChung");
					this.OnTrieuChungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_DSKhamBenh", Storage="_DSKhamBenhs", ThisKey="MaBN", OtherKey="MaBN")]
		public EntitySet<DSKhamBenh> DSKhamBenhs
		{
			get
			{
				return this._DSKhamBenhs;
			}
			set
			{
				this._DSKhamBenhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = this;
		}
		
		private void detach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.BenhNhan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CachDung")]
	public partial class CachDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCD;
		
		private string _HuongDan;
		
		private EntitySet<DSKhamBenh> _DSKhamBenhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCDChanging(string value);
    partial void OnMaCDChanged();
    partial void OnHuongDanChanging(string value);
    partial void OnHuongDanChanged();
    #endregion
		
		public CachDung()
		{
			this._DSKhamBenhs = new EntitySet<DSKhamBenh>(new Action<DSKhamBenh>(this.attach_DSKhamBenhs), new Action<DSKhamBenh>(this.detach_DSKhamBenhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuongDan", DbType="NVarChar(50)")]
		public string HuongDan
		{
			get
			{
				return this._HuongDan;
			}
			set
			{
				if ((this._HuongDan != value))
				{
					this.OnHuongDanChanging(value);
					this.SendPropertyChanging();
					this._HuongDan = value;
					this.SendPropertyChanged("HuongDan");
					this.OnHuongDanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CachDung_DSKhamBenh", Storage="_DSKhamBenhs", ThisKey="MaCD", OtherKey="MaCD")]
		public EntitySet<DSKhamBenh> DSKhamBenhs
		{
			get
			{
				return this._DSKhamBenhs;
			}
			set
			{
				this._DSKhamBenhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.CachDung = this;
		}
		
		private void detach_DSKhamBenhs(DSKhamBenh entity)
		{
			this.SendPropertyChanging();
			entity.CachDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DonVi")]
	public partial class DonVi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonVi;
		
		private string _TenDonVi;
		
		private EntitySet<Thuoc> _Thuocs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonViChanging(string value);
    partial void OnMaDonViChanged();
    partial void OnTenDonViChanging(string value);
    partial void OnTenDonViChanged();
    #endregion
		
		public DonVi()
		{
			this._Thuocs = new EntitySet<Thuoc>(new Action<Thuoc>(this.attach_Thuocs), new Action<Thuoc>(this.detach_Thuocs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonVi", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonVi
		{
			get
			{
				return this._MaDonVi;
			}
			set
			{
				if ((this._MaDonVi != value))
				{
					this.OnMaDonViChanging(value);
					this.SendPropertyChanging();
					this._MaDonVi = value;
					this.SendPropertyChanged("MaDonVi");
					this.OnMaDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(50)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this.OnTenDonViChanging(value);
					this.SendPropertyChanging();
					this._TenDonVi = value;
					this.SendPropertyChanged("TenDonVi");
					this.OnTenDonViChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DonVi_Thuoc", Storage="_Thuocs", ThisKey="MaDonVi", OtherKey="MaDonVi")]
		public EntitySet<Thuoc> Thuocs
		{
			get
			{
				return this._Thuocs;
			}
			set
			{
				this._Thuocs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonVi = this;
		}
		
		private void detach_Thuocs(Thuoc entity)
		{
			this.SendPropertyChanging();
			entity.DonVi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DSKhamBenh")]
	public partial class DSKhamBenh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKB;
		
		private string _MaBenh;
		
		private string _MaThuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private string _MaCD;
		
		private string _MaBN;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _ThanhTien;
		
		private EntityRef<Benh> _Benh;
		
		private EntityRef<BenhNhan> _BenhNhan;
		
		private EntityRef<CachDung> _CachDung;
		
		private EntityRef<Thuoc> _Thuoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKBChanging(string value);
    partial void OnMaKBChanged();
    partial void OnMaBenhChanging(string value);
    partial void OnMaBenhChanged();
    partial void OnMaThuocChanging(string value);
    partial void OnMaThuocChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    partial void OnMaCDChanging(string value);
    partial void OnMaCDChanged();
    partial void OnMaBNChanging(string value);
    partial void OnMaBNChanged();
    partial void OnNgayKhamChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhamChanged();
    partial void OnThanhTienChanging(System.Nullable<int> value);
    partial void OnThanhTienChanged();
    #endregion
		
		public DSKhamBenh()
		{
			this._Benh = default(EntityRef<Benh>);
			this._BenhNhan = default(EntityRef<BenhNhan>);
			this._CachDung = default(EntityRef<CachDung>);
			this._Thuoc = default(EntityRef<Thuoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKB", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKB
		{
			get
			{
				return this._MaKB;
			}
			set
			{
				if ((this._MaKB != value))
				{
					this.OnMaKBChanging(value);
					this.SendPropertyChanging();
					this._MaKB = value;
					this.SendPropertyChanged("MaKB");
					this.OnMaKBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenh", DbType="VarChar(10)")]
		public string MaBenh
		{
			get
			{
				return this._MaBenh;
			}
			set
			{
				if ((this._MaBenh != value))
				{
					if (this._Benh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBenhChanging(value);
					this.SendPropertyChanging();
					this._MaBenh = value;
					this.SendPropertyChanged("MaBenh");
					this.OnMaBenhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10)")]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					if (this._Thuoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThuocChanging(value);
					this.SendPropertyChanging();
					this._MaThuoc = value;
					this.SendPropertyChanged("MaThuoc");
					this.OnMaThuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="VarChar(10)")]
		public string MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					if (this._CachDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCDChanging(value);
					this.SendPropertyChanging();
					this._MaCD = value;
					this.SendPropertyChanged("MaCD");
					this.OnMaCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10)")]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					if (this._BenhNhan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBNChanging(value);
					this.SendPropertyChanging();
					this._MaBN = value;
					this.SendPropertyChanged("MaBN");
					this.OnMaBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this.OnThanhTienChanging(value);
					this.SendPropertyChanging();
					this._ThanhTien = value;
					this.SendPropertyChanged("ThanhTien");
					this.OnThanhTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Benh_DSKhamBenh", Storage="_Benh", ThisKey="MaBenh", OtherKey="MaBenh", IsForeignKey=true)]
		public Benh Benh
		{
			get
			{
				return this._Benh.Entity;
			}
			set
			{
				Benh previousValue = this._Benh.Entity;
				if (((previousValue != value) 
							|| (this._Benh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Benh.Entity = null;
						previousValue.DSKhamBenhs.Remove(this);
					}
					this._Benh.Entity = value;
					if ((value != null))
					{
						value.DSKhamBenhs.Add(this);
						this._MaBenh = value.MaBenh;
					}
					else
					{
						this._MaBenh = default(string);
					}
					this.SendPropertyChanged("Benh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BenhNhan_DSKhamBenh", Storage="_BenhNhan", ThisKey="MaBN", OtherKey="MaBN", IsForeignKey=true)]
		public BenhNhan BenhNhan
		{
			get
			{
				return this._BenhNhan.Entity;
			}
			set
			{
				BenhNhan previousValue = this._BenhNhan.Entity;
				if (((previousValue != value) 
							|| (this._BenhNhan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BenhNhan.Entity = null;
						previousValue.DSKhamBenhs.Remove(this);
					}
					this._BenhNhan.Entity = value;
					if ((value != null))
					{
						value.DSKhamBenhs.Add(this);
						this._MaBN = value.MaBN;
					}
					else
					{
						this._MaBN = default(string);
					}
					this.SendPropertyChanged("BenhNhan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CachDung_DSKhamBenh", Storage="_CachDung", ThisKey="MaCD", OtherKey="MaCD", IsForeignKey=true)]
		public CachDung CachDung
		{
			get
			{
				return this._CachDung.Entity;
			}
			set
			{
				CachDung previousValue = this._CachDung.Entity;
				if (((previousValue != value) 
							|| (this._CachDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CachDung.Entity = null;
						previousValue.DSKhamBenhs.Remove(this);
					}
					this._CachDung.Entity = value;
					if ((value != null))
					{
						value.DSKhamBenhs.Add(this);
						this._MaCD = value.MaCD;
					}
					else
					{
						this._MaCD = default(string);
					}
					this.SendPropertyChanged("CachDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Thuoc_DSKhamBenh", Storage="_Thuoc", ThisKey="MaThuoc", OtherKey="MaThuoc", IsForeignKey=true)]
		public Thuoc Thuoc
		{
			get
			{
				return this._Thuoc.Entity;
			}
			set
			{
				Thuoc previousValue = this._Thuoc.Entity;
				if (((previousValue != value) 
							|| (this._Thuoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Thuoc.Entity = null;
						previousValue.DSKhamBenhs.Remove(this);
					}
					this._Thuoc.Entity = value;
					if ((value != null))
					{
						value.DSKhamBenhs.Add(this);
						this._MaThuoc = value.MaThuoc;
					}
					else
					{
						this._MaThuoc = default(string);
					}
					this.SendPropertyChanged("Thuoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TaiKhoan")]
	public partial class TaiKhoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _PassWord;
		
		private System.Nullable<int> _xoa;
		
		private string _TinhTrang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    partial void OnxoaChanging(System.Nullable<int> value);
    partial void OnxoaChanged();
    partial void OnTinhTrangChanging(string value);
    partial void OnTinhTrangChanged();
    #endregion
		
		public TaiKhoan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="NVarChar(50)")]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_xoa", DbType="Int")]
		public System.Nullable<int> xoa
		{
			get
			{
				return this._xoa;
			}
			set
			{
				if ((this._xoa != value))
				{
					this.OnxoaChanging(value);
					this.SendPropertyChanging();
					this._xoa = value;
					this.SendPropertyChanged("xoa");
					this.OnxoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TinhTrang", DbType="VarChar(10)")]
		public string TinhTrang
		{
			get
			{
				return this._TinhTrang;
			}
			set
			{
				if ((this._TinhTrang != value))
				{
					this.OnTinhTrangChanging(value);
					this.SendPropertyChanging();
					this._TinhTrang = value;
					this.SendPropertyChanged("TinhTrang");
					this.OnTinhTrangChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamSo")]
	public partial class ThamSo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private System.Nullable<int> _SoLuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
		
		public ThamSo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this.OnSoLuongChanging(value);
					this.SendPropertyChanging();
					this._SoLuong = value;
					this.SendPropertyChanged("SoLuong");
					this.OnSoLuongChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class cau13Result
	{
		
		private string _MaKB;
		
		private string _MaBenh;
		
		private string _MaThuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private string _MaCD;
		
		private string _MaBN;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _ThanhTien;
		
		public cau13Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKB
		{
			get
			{
				return this._MaKB;
			}
			set
			{
				if ((this._MaKB != value))
				{
					this._MaKB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenh", DbType="VarChar(10)")]
		public string MaBenh
		{
			get
			{
				return this._MaBenh;
			}
			set
			{
				if ((this._MaBenh != value))
				{
					this._MaBenh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10)")]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this._MaThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="VarChar(10)")]
		public string MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this._MaCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10)")]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this._MaBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this._NgayKham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
	}
	
	public partial class cau15Result
	{
		
		private string _MaBN;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NamSinh;
		
		private string _DiaChi;
		
		private string _TrieuChung;
		
		public cau15Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this._MaBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this._HoTen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(10)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this._GioiTinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamSinh", DbType="Date")]
		public System.Nullable<System.DateTime> NamSinh
		{
			get
			{
				return this._NamSinh;
			}
			set
			{
				if ((this._NamSinh != value))
				{
					this._NamSinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this._DiaChi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrieuChung", DbType="NVarChar(50)")]
		public string TrieuChung
		{
			get
			{
				return this._TrieuChung;
			}
			set
			{
				if ((this._TrieuChung != value))
				{
					this._TrieuChung = value;
				}
			}
		}
	}
	
	public partial class cau16Result
	{
		
		private string _MaKB;
		
		private string _MaBenh;
		
		private string _MaThuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private string _MaCD;
		
		private string _MaBN;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _ThanhTien;
		
		public cau16Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKB
		{
			get
			{
				return this._MaKB;
			}
			set
			{
				if ((this._MaKB != value))
				{
					this._MaKB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBenh", DbType="VarChar(10)")]
		public string MaBenh
		{
			get
			{
				return this._MaBenh;
			}
			set
			{
				if ((this._MaBenh != value))
				{
					this._MaBenh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10)")]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this._MaThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCD", DbType="VarChar(10)")]
		public string MaCD
		{
			get
			{
				return this._MaCD;
			}
			set
			{
				if ((this._MaCD != value))
				{
					this._MaCD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10)")]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this._MaBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this._NgayKham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
	}
	
	public partial class cau17Result
	{
		
		private string _MaKB;
		
		private string _TenBenh;
		
		private string _TenThuoc;
		
		private System.Nullable<int> _SoLuong;
		
		private string _HuongDan;
		
		private string _MaBN;
		
		private System.Nullable<System.DateTime> _NgayKham;
		
		private System.Nullable<int> _ThanhTien;
		
		public cau17Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKB", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaKB
		{
			get
			{
				return this._MaKB;
			}
			set
			{
				if ((this._MaKB != value))
				{
					this._MaKB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBenh", DbType="NVarChar(50)")]
		public string TenBenh
		{
			get
			{
				return this._TenBenh;
			}
			set
			{
				if ((this._TenBenh != value))
				{
					this._TenBenh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this._TenThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
		public System.Nullable<int> SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HuongDan", DbType="NVarChar(50)")]
		public string HuongDan
		{
			get
			{
				return this._HuongDan;
			}
			set
			{
				if ((this._HuongDan != value))
				{
					this._HuongDan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBN", DbType="VarChar(10)")]
		public string MaBN
		{
			get
			{
				return this._MaBN;
			}
			set
			{
				if ((this._MaBN != value))
				{
					this._MaBN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="Date")]
		public System.Nullable<System.DateTime> NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this._NgayKham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThanhTien", DbType="Int")]
		public System.Nullable<int> ThanhTien
		{
			get
			{
				return this._ThanhTien;
			}
			set
			{
				if ((this._ThanhTien != value))
				{
					this._ThanhTien = value;
				}
			}
		}
	}
	
	public partial class cau18Result
	{
		
		private System.Nullable<System.DateTime> _ngaykham;
		
		private System.Nullable<int> _thanhtien;
		
		private System.Nullable<int> _soluong;
		
		public cau18Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaykham", DbType="Date")]
		public System.Nullable<System.DateTime> ngaykham
		{
			get
			{
				return this._ngaykham;
			}
			set
			{
				if ((this._ngaykham != value))
				{
					this._ngaykham = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thanhtien", DbType="Int")]
		public System.Nullable<int> thanhtien
		{
			get
			{
				return this._thanhtien;
			}
			set
			{
				if ((this._thanhtien != value))
				{
					this._thanhtien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
	}
	
	public partial class cau19Result
	{
		
		private string _MaThuoc;
		
		private string _TenThuoc;
		
		private string _TenDonVi;
		
		private System.Nullable<int> _sl;
		
		public cau19Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThuoc", DbType="VarChar(10)")]
		public string MaThuoc
		{
			get
			{
				return this._MaThuoc;
			}
			set
			{
				if ((this._MaThuoc != value))
				{
					this._MaThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThuoc", DbType="NVarChar(50)")]
		public string TenThuoc
		{
			get
			{
				return this._TenThuoc;
			}
			set
			{
				if ((this._TenThuoc != value))
				{
					this._TenThuoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonVi", DbType="NVarChar(50)")]
		public string TenDonVi
		{
			get
			{
				return this._TenDonVi;
			}
			set
			{
				if ((this._TenDonVi != value))
				{
					this._TenDonVi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sl", DbType="Int")]
		public System.Nullable<int> sl
		{
			get
			{
				return this._sl;
			}
			set
			{
				if ((this._sl != value))
				{
					this._sl = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
